### PR TITLE
Fix Inner/Outer Stairs translation

### PR DESCRIPTION
**Pull request by louisroyer**
Fix Inner/Outer Stairs translation <s>if minetest/minetest_game/pull/2584 is accepted (do not merge until MTG PR is merged)</s>.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
Looks like I created some conflicts, I can fix when that PR is merged if you don't want to bother

**Comment by louisroyer** [comment]
Don't worry, I will resolve conflicts this when the MTG PR is merged.

**Comment by louisroyer** [comment]
Rebased, and updated since the order of inner and outer has been reversed on `stairs` api. Waiting for a last review on minetest-game.

**Comment by LoneWolfHT** [comment]
Looks like you finally got it merged lol

**Pull request merged**
